spring:
  datasource:
    url: jdbc:h2:mem:db
    driverClassName: org.h2.Driver
    username: test
    password: test
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
server:
  port: 3000